### ISSUE TITLE
List baud rate used in status

### ISSUE THREAD

**Issue by mpserafin** [Security-Industry-Association/libosdp-conformance#14]
I am having trouble getting a reader to respond and I think it has to do with the baud rate that is being used.  The status lists the pd_address, but I think having the baud rate listed would be helpful as well.

Timestamp: 1489018109.317873153 Wed Mar  8 16:08:29 2017
{
      "last_update" : "Wed Mar  8 16:08:27 2017",
             "role" : "0",
                "#" : "0=CP 1=PD 2=MON",
       "pd_address" : "00",

**Comment by rsgmodelworks** [comment]
fixed in 0.1 build 1
