### ISSUE TITLE
master branch does not build

### ISSUE THREAD

**Issue by mattiasclaesson** [Security-Industry-Association/libosdp-conformance#25]
I did clone the repository from github.
But the aes.h include and implementation is nowhere to be found.
`(cd src-lib; make build; cd ..)
make[1]: Entering directory `/opt/osdp-conformance/setup/libosdp-conformance/src-lib'
gcc -DOSDP_CONFORMANCE -I/opt/osdp-conformance/include -I /tester/current/include -c -g -I../include -Wall -Werror \
          oosdp_actions.c
oosdp_actions.c:27:17: fatal error: aes.h: No such file or directory
 #include <aes.h>
                 ^
compilation terminated.
`
Then I did download the zipped file from
open-osdp-0.1-Build-10.zip

and found the aes.h and .c files.

Also I get a similar issue when trying to build the osdp-tls
(cd src-tls; make build; cd ..)
make[1]: Entering directory `/opt/osdp-conformance/setup/libosdp-conformance/src-tls'
gcc -I /opt/tester/include -c -g -I. -I../include -Wall -Werror \
          osdp-net-client.c
osdp-net-client.c:38:27: fatal error: gnutls/gnutls.h: No such file or directory
 #include <gnutls/gnutls.h>
                           ^
compilation terminated.

I do however think I did install the correct library dependencies.

**Comment by rsgmodelworks** [comment]
fixed. doc updated to describe use of tiny-AES-c (which also recently changed so modified to match that.)  Remember the secure channel code is a work in progress.
