### ISSUE TITLE
open-osdp: command not found

### ISSUE THREAD

**Issue by Hector-IoT** [Security-Industry-Association/libosdp-conformance#26]
After a clean installation i get: 

sudo: /opt/osdp-conformance/bin/open-osdp: command not found

**Comment by PhoenixBaymax** [comment]
i guess there is some error when u make, so the open-osdp file is not created.

**Comment by rsgmodelworks** [comment]
the make file doesn't install it.  that is on the to-do list.  the documentation was supposed to tell you this (checking that now.)

**Comment by rsgmodelworks** [comment]
there is now a "make package" option that makes a proper debian package and installs the relevant files.
