### ISSUE TITLE
Test-ACU.html Display report: report.log file not exist

### ISSUE THREAD

**Issue by PhoenixBaymax** [Security-Industry-Association/libosdp-conformance#29]
Display report is to run "sudo -n cat /opt/osdp-conformance/log/report.log", but I can not find the file.I find another report.log in /opt/osdp-conformance/results. Where is the log/report.log?

**Comment by rsgmodelworks** [comment]
you need to run the generate report command first.

**Comment by rsgmodelworks** [comment]
fix checked in and being tested.

**Comment by PhoenixBaymax** [comment]
I had "Generate",but the report.log was in /opt/osdp-conformance/results/report.log.
