### ISSUE TITLE
build and doc

### ISSUE THREAD

**Issue by rsgmodelworks** [Security-Industry-Association/libosdp-conformance#3]
need more doc on building;
remove clang dependancy;
doc packages needed e.g. jansson

**Comment by rsgmodelworks** [comment]
doc/build/build-CONFORMANCE.txt provides some data but is incomplete.

**Comment by mpserafin** [comment]
The name of the tar file is not correct in the build notes document:

This:
  tar xzvf /opt/osdp-conformance/setup/libosdp-conformance/release-libosdp.tgz

Should be:
  tar xzvf /opt/osdp-conformance/setup/libosdp-conformance/release-osdp-conformance.tgz

**Comment by rsgmodelworks** [comment]
Documentation updated in 0.70, see libosdp-conformance-guide.pdf
