### ISSUE TITLE
Test-ACU.html osdp_PDID file not found

### ISSUE THREAD

**Issue by PhoenixBaymax** [Security-Industry-Association/libosdp-conformance#30]
using test-acu.html to test pd, run testcase 

050-09-13 | Test | Configuration Address (7F)

060-03-01 | Test | Command: osdp_ID

but open-osdp run with a tip: 
sh: 1: /opt/osdp-conformance/ACU-actions/osdp_PDID: not found

I can not find the ACU-actions dir and the osdp_PDID script file.
Is the osdp_PDID file  generated by us or from other way?

**Comment by rsgmodelworks** [comment]
stub actions checked in.
