### ISSUE TITLE
Test-ACU.html osdp_NAK not found

### ISSUE THREAD

**Issue by PhoenixBaymax** [Security-Industry-Association/libosdp-conformance#31]
using test-acu.html to test pd, run testcase

060-06-01 |  Test | Command: ISTAT
060-07-01 |  Test | Command: osdp_OSTAT
060-09-01 |  Test | Command: osdp_OUT
060-10-01 | Test | LED Test (Red)
060-10-04 | Test | LED Test (Green)
060-12-01 | Not Supported Test | Cmd: TEXT
060-20-01 | 3-22-1 | Cmd: ACURXSIZE
060-18-01 | Test | Command: osdp_MFG

but open-osdp run with a tip:
sh: 1: /opt/osdp-conformance/ACU-actions/osdp_NAK: not found

I can not find the ACU-actions dir and the osdp_NAK script file.
Is the osdp_NAK file generated by us or from other way?

**Comment by rsgmodelworks** [comment]
stub versions of all action routines now created in build process, which means be careful your custom actions would be lost in a reload.

**Comment by rsgmodelworks** [comment]
checked in
