### ISSUE TITLE
action scirpts in dir actions exists some error

### ISSUE THREAD

**Issue by AKing23T** [Security-Industry-Association/libosdp-conformance#33]
the content in osdp_NAK is as below:
mkdir -p /opt/osdp-conformance/lib/actions.log
echo >>/opt/osdp-conformance/lib/actions.log osdp_NAK called $1 $2 $3 $4 $5 $6 $7 $8

in first line,actions.log is a dir,but in second line, actions.log was treated as a file.When the script runs, the console show the error "/opt/osdp-conformance/run/ACU-actions/osdp_NAK: line 3: /opt/osdp-conformance/lib/actions.log: Is a directory".

there are the same problems in the other script of actions.

**Comment by rsgmodelworks** [comment]
fixed.
