### ISSUE TITLE
three questions about osdp_comset 

### ISSUE THREAD

**Issue by AKing23T** [Security-Industry-Association/libosdp-conformance#35]
I have two questions:
1. Why is the "ADDR" data in the format packet ox7f always to use osdp_comset to set new addr and new bps?
2. Whether is it necessary to add a sleep between send_messge_ex and init_serial in function send_comset, sometimes it exists the error like "***sequence number mismatch got 2 expected 0".
3. Is it 0x00 or 0x01 for seq in new communication after osdp_comset reply?

**Comment by rsgmodelworks** [comment]
the test case I coded used 0x7F.  that's not the only option.  there's a command that allows you to set all the parameters.  the sleep is there to survive the glitch when the ACU changes it's own serial port speed.  Exactly what sequence number happens at the new/address speed is vague.  IMO it should restart at zero.  code migth not do that cleanly.
