### ISSUE TITLE
When will this library be updated for the new character encoding?

### ISSUE THREAD

**Issue by patrick-compass** [Security-Industry-Association/libosdp-conformance#36]
The latest specification altered the character encoding from fixed-width 8 bit ASCII characters, to variable-width UTF-8 characters.

When can we expect to see an update for this monumental change?

**Comment by rsgmodelworks** [comment]
not sure what you are talking about, SIA OSDP 2.2 and 2.2.2 still use 8 bit ascii as far as i know.
