### ISSUE TITLE
OSDP_ISTATR sent in plain text in SC

### ISSUE THREAD

**Issue by sosroz** [Security-Industry-Association/libosdp-conformance#37]
When in SC, the OSDP_ISTATR response is being sent int the clear.

The fix would be to update _process_osdp_message_ in _src-lib/oo-util.c_ to change 

_status = send_message (context, OSDP_ISTATR, p_card.addr,
         &current_length, sizeof (osdp_istat_response_data), osdp_istat_response_data);_

to

_status = send_message_ex (context, OSDP_ISTATR, p_card.addr,
                         &current_length, sizeof (osdp_istat_response_data), osdp_istat_response_data, OSDP_SEC_SCS_18, 0, NULL);_

**Comment by rsgmodelworks** [comment]
fixed
