### ISSUE TITLE
osdp_KEEPACTIVE send wrong command

### ISSUE THREAD

**Issue by DmitriyButkevich** [Security-Industry-Association/libosdp-conformance#47]
in protocol SIA-OSDP v.2.2  there must be 2 bytes "Card keep-alive time in milliseconds" (Table 29 – Keep Reader Active (osdp_KEEPACTIVE))
But actually it sends only A7 and then CRC without this 2 bytes:
![image](https://user-images.githubusercontent.com/131346626/233304064-10af418e-5b22-4008-a7e9-5920f73007b9.png)
1.32-Build-4

**Comment by rsgmodelworks** [comment]
this has been fixed.
